# Generated by Django 3.2.12 on 2023-12-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productfilter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
